In [1]:
from qiskit.circuit.library import U3Gate
import numpy as np
pi = np.pi
u3  = U3Gate(0, pi, 0)
u3.to_matrix()

array([[ 1.+0.0000000e+00j,  0.-0.0000000e+00j],
       [-0.+0.0000000e+00j, -1.+1.2246468e-16j]])

In [2]:
# <!-- 假设按照0, 1,2的顺序 -->

In [3]:
def tensor(ms):
    ms = list(ms)
    ms.reverse()
    sm = ms[0]
    for m in ms[1:]:
        sm = np.kron(sm ,m)
    return sm

In [4]:
t = np.kron(u3, np.identity(2**2))  #10, 11 旋转 0 比特 （大端）
# np.round(t)
t == 1

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [5]:
def p(mat):
    return np.round(mat) == -1

In [6]:
from qiskit.opflow.primitive_ops.matrix_op import MatrixOp
def permute(mat, index):
    mat = MatrixOp(mat)
    mat = mat.permute(index).to_matrix()
    return mat

In [7]:
I2 = np.identity(2**1)

In [8]:
p(permute(tensor([u3, I2, I2]), [0,1,2]))
# 012, 021, 120, 102, 210, 201

array([[False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True]])

In [9]:
p(permute(tensor([u3, I2, I2]), [0,2,1]))
# 012, 021, 120, 102, 210, 201

array([[False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True]])

In [10]:
p(permute(tensor([u3, I2, I2]), [1,0,2]))

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [11]:
p(permute(tensor([u3, I2, I2]), [1,2,0]))

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [12]:
p(permute(tensor([u3, I2, I2]), [2,0,1])) 

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [13]:
p(permute(tensor([u3, I2, I2]), [2,1,0])) 

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [14]:
p(tensor([I2, u3, I2])) # 102,120
# The qubit at index j should be permuted to position permutation[j].

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [15]:
p(tensor([I2, I2, u3]))  #201,210

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [16]:
p(tensor([u3, I2, I2]))  # 012, 021,
# The qubit at index j should be permuted to position permutation[j].

array([[False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True]])